import * as vscode from 'vscode';
import * as fs     from 'fs';
import * as path   from 'path';
import { SymbolIndexer }       from './SymbolIndexer';
import { BlastRadiusAnalyzer } from './BlastRadiusAnalyzer';
import { FileSummarizer }      from './FileSummarizer';

// Single job: write CLAUDE.md to the repo root
// Claude Code, Cursor, and ChatGPT all read this file automatically
export class ClaudeMdGenerator {

  constructor(
    private readonly symbols:   SymbolIndexer,
    private readonly blast:     BlastRadiusAnalyzer,
    private readonly summaries: FileSummarizer,
  ) {}

  // Generate and write CLAUDE.md — opens it in the editor when done
  async generate(): Promise<void> {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders) {
      vscode.window.showWarningMessage('CodeSec: No workspace open.');
      return;
    }

    const root = folders[0].uri.fsPath;
    const dest = path.join(root, 'CLAUDE.md');

    await vscode.window.withProgress(
      { location: vscode.ProgressLocation.Notification, title: 'CodeSec: Generating CLAUDE.md…', cancellable: false },
      async () => {
        const content = await this.buildContent(root);
        fs.writeFileSync(dest, content, 'utf8');
      }
    );

    // Open CLAUDE.md so the user can review it before committing
    const doc = await vscode.workspace.openTextDocument(dest);
    await vscode.window.showTextDocument(doc);

    vscode.window.showInformationMessage(
      'CodeSec: CLAUDE.md generated — commit this file so every AI tool understands your project.',
      'What is CLAUDE.md?'
    ).then(choice => {
      if (choice === 'What is CLAUDE.md?') {
        vscode.env.openExternal(
          vscode.Uri.parse('https://docs.anthropic.com/en/docs/claude-code/memory')
        );
      }
    });
  }

  // Build the full CLAUDE.md markdown content
  private async buildContent(root: string): Promise<string> {
    const projectName = path.basename(root);
    const fileSummaries = this.summaries.getSummaries();
    const allSymbols    = await this.symbols.getSymbols();

    const sections: string[] = [];

    // ── Header ───────────────────────────────────────────────────────────────
    sections.push(`# ${projectName}`);
    sections.push('');
    sections.push('> Auto-generated by [CodeSec](https://github.com/your-org/codesec).');
    sections.push('> Regenerate: `Cmd+Shift+P → CodeSec: Generate CLAUDE.md`');
    sections.push('');

    // ── Architecture ─────────────────────────────────────────────────────────
    sections.push('## Architecture');
    sections.push('');
    sections.push('```');
    sections.push(this.buildFolderTree(root, fileSummaries));
    sections.push('```');
    sections.push('');

    // ── File Responsibilities ─────────────────────────────────────────────────
    if (fileSummaries.size > 0) {
      sections.push('## File Responsibilities');
      sections.push('');
      sections.push('| File | Single Responsibility |');
      sections.push('|------|----------------------|');
      for (const [file, summary] of fileSummaries) {
        sections.push(`| \`${file}\` | ${summary.replace(/\|/g, '\\|')} |`);
      }
      sections.push('');
    }

    // ── Key Patterns ──────────────────────────────────────────────────────────
    sections.push('## Key Patterns — Read Before Editing');
    sections.push('');
    sections.push('- **Single Responsibility** — every class/file has one clearly stated job');
    sections.push('- **Dependency Injection** — deps are injected via constructor, never instantiated inside');
    sections.push('- **Interface-driven** — depend on interfaces in `src/interfaces/`, not concrete classes');
    sections.push('- **Open/Closed** — add new rules/scanners by creating new files, not editing existing ones');
    sections.push('- **One-way data flow** — rules → scanners → orchestrator → publishers (never reversed)');
    sections.push('');

    // ── Where to Add Things ───────────────────────────────────────────────────
    sections.push('## Where to Add Things');
    sections.push('');
    sections.push('**New static rule** (detect a new anti-pattern or security issue):');
    sections.push('1. Open `src/rules/<language>Rules.ts`');
    sections.push('2. Add one object to the `RULES` array');
    sections.push('3. `npm run compile` — done, nothing else changes');
    sections.push('');
    sections.push('**New scanner** (new analysis type):');
    sections.push('1. Create `src/scanners/MyScanner.ts` implementing `IScanner`');
    sections.push('2. Add it to `AnalysisOrchestrator` constructor and `run()` method');
    sections.push('3. Inject in `extension.ts`');
    sections.push('');
    sections.push('**New language**:');
    sections.push('1. Create `src/rules/myLanguageRules.ts`');
    sections.push('2. Add one `else if` branch in `StaticScanner.scan()`');
    sections.push('3. Add language to `package.json` → `codeSec.languages` default');
    sections.push('');

    // ── High Blast Radius Files ───────────────────────────────────────────────
    const highImpact = await this.getHighImpactFiles();
    if (highImpact.length > 0) {
      sections.push('## High Blast Radius Files — Be Careful');
      sections.push('');
      sections.push('Changing these files affects many others. Check dependents before editing.');
      sections.push('');
      for (const f of highImpact) {
        sections.push(`- \`${f.file}\` — ${f.blastRadius} file(s) depend on it`);
      }
      sections.push('');
    }

    // ── Symbol Index ──────────────────────────────────────────────────────────
    if (allSymbols.length > 0) {
      sections.push('## Symbol Index');
      sections.push('');
      sections.push('Every exported function, class, and interface and where to find it:');
      sections.push('');
      sections.push('```');

      // Group symbols by file for readability
      const byFile = new Map<string, typeof allSymbols>();
      for (const sym of allSymbols) {
        const existing = byFile.get(sym.file) ?? [];
        existing.push(sym);
        byFile.set(sym.file, existing);
      }

      for (const [file, syms] of byFile) {
        sections.push(`// ${file}`);
        for (const s of syms) {
          sections.push(`  ${s.kind.padEnd(12)} ${s.name.padEnd(35)} L${s.line + 1}`);
        }
        sections.push('');
      }

      sections.push('```');
      sections.push('');
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    sections.push('---');
    sections.push(`*Generated ${new Date().toLocaleString()} by CodeSec*`);

    return sections.join('\n');
  }

  // Build a folder tree with inline summaries for the Architecture section
  private buildFolderTree(root: string, summaries: Map<string, string>): string {
    const srcPath = path.join(root, 'src');
    if (!fs.existsSync(srcPath)) return `${path.basename(root)}/`;

    const lines: string[] = [`${path.basename(root)}/`, '  src/'];

    try {
      const walk = (dir: string, prefix: string, depth: number): void => {
        if (depth > 4) return;

        let entries: fs.Dirent[];
        try {
          entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
          return;
        }

        // Directories first, then files
        const dirs  = entries.filter(e => e.isDirectory() && !e.name.startsWith('.'));
        const files = entries.filter(e => e.isFile() && e.name.endsWith('.ts') && !e.name.endsWith('.d.ts'));

        for (const d of dirs) {
          if (['node_modules', 'out', 'dist'].includes(d.name)) continue;
          lines.push(`${prefix}├── ${d.name}/`);
          walk(path.join(dir, d.name), prefix + '│   ', depth + 1);
        }

        for (const f of files) {
          const rel     = path.relative(root, path.join(dir, f.name));
          const summary = summaries.get(rel) ?? '';
          const short   = summary.length > 45 ? summary.slice(0, 42) + '…' : summary;
          lines.push(`${prefix}├── ${f.name.padEnd(35)} ${short}`);
        }
      };

      walk(srcPath, '    │   ', 0);
    } catch { /* ignore */ }

    return lines.join('\n');
  }

  // Find the top 10 files with the highest blast radius
  private async getHighImpactFiles(): Promise<Array<{ file: string; blastRadius: number }>> {
    const uris = await vscode.workspace.findFiles(
      '**/*.{ts,tsx,js,jsx,py,java}',
      '{**/node_modules/**,**/dist/**,**/out/**}'
    );

    const scored: Array<{ file: string; blastRadius: number }> = [];

    // Only check first 30 files to keep generation fast
    for (const uri of uris.slice(0, 30)) {
      try {
        const node = await this.blast.getBlastRadius(uri);
        if (node.blastRadius >= 3) {
          scored.push({ file: node.file, blastRadius: node.blastRadius });
        }
      } catch { /* skip */ }
    }

    return scored
      .sort((a, b) => b.blastRadius - a.blastRadius)
      .slice(0, 10);
  }
}